[package]
name = "prompt_to_ai"
version = "0.1.0"
edition = "2024"

[dependencies]
arboard = "3.6.1"
clap = { version = "4.5.48", features = ["derive"] }
git2 = "0.20.2"
regex = "1.11.3"

[[bin]]
name = "pai"  
path = "src/main.rs"